import Head from "next/head";
import CommonCal from "./Calculator/CommonCal";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dail Count 데일리 카운트 - 당신의 일상 속 계산기</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommonCal></CommonCal>
    </>
  );
}
